### PR TITLE
Pen red msvs

### PR DESCRIPTION
**Pull request by shirokobrod**
Add possibility for generating Visual Studio projects for windows. VC does not have <dirent> module. Instead C++17 <filesystem> module is used. M_PI macro is not portable. Instead C++20 <numbers> module is used. These modules make code portable but require compiler implemented C++20 standard. Actually this modification generates projects for MSVS starting from 2019.

### CODE REVIEW

**Comment by vigial** [comment]
Thanks for your pull request.

We had planned to add support for windows, thus your contribution will be very useful. The reason why we restricted the code to C++11 standard is because many clusters and other infrastructures uses a very old compilers with no support for later standards... But I think it is ok to use a newer standard for windows, as these infrastructures usually use Linux.

We will check the proposed changes as soon as possible and merge the pull request.

**Comment by vigial** [comment]
I have removed the error construction files during the compiling step because is not necessary anymore and will simplify the compatibility. The changes can be found in the pull request cf93daf47213e75fef6a9bc4c7e81f997300cfb3.  Now, there are only 3 conflicting files with your branch. If I am right, they only requires some simple changes:

- src/CMakeLists.txt : Requires to remove the error creation files code:
```
# Generate error list
add_custom_command(
  OUTPUT
  ${PROJECT_SOURCE_DIR}/config/errors/eenum.h
  ${PROJECT_SOURCE_DIR}/config/errors/emess.h
  if (NOT MSVC)  
	DEPENDS ${CMAKE_BINARY_DIR}/utilities/createErrors
	COMMAND ${CMAKE_BINARY_DIR}/utilities/createErrors
  else()
	DEPENDS ${CMAKE_BINARY_DIR}/utilities/createErrors.exe
	COMMAND cd ${CMAKE_BINARY_DIR} & ${CMAKE_BINARY_DIR}/utilities/createErrors.exe
  endif()
  WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}/config/errors
  )
# Create target for error headers
add_custom_target(
  errorHeaders
  DEPENDS ${PROJECT_SOURCE_DIR}/config/errors/eenum.h
  DEPENDS ${PROJECT_SOURCE_DIR}/config/errors/emess.h  
  )
```

- src/utilities/CMakeLists.txt: Needs to remove the compilation of createErrors target:

```
#  Error list generator
#############################
add_executable(createErrors ${PROJECT_SOURCE_DIR}/utilities/errors/createErrors.cpp)  
set_target_properties(createErrors PROPERTIES
	RUNTIME_OUTPUT_DIRECTORY_DEBUG $<1:${CMAKE_BINARY_DIR}/utilities>
	RUNTIME_OUTPUT_DIRECTORY_RELEASE $<1:${CMAKE_BINARY_DIR}/utilities>
	RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO $<1:${CMAKE_BINARY_DIR}/utilities>
	RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL $<1:${CMAKE_BINARY_DIR}/utilities>
)
```

- src/utilities/errors/createErrors.cpp: This file must be removed


Please, can you adapt your branch to the new version and check if it still compile properly?

**Comment by shirokobrod** [comment]
I have attached a diff between the original branch and main. After your
update the conflict differences are:
            .src/CMakeLists.txt
add /arch:AVX2 and /MP compiler options (I remove /std:c++latest compiler
flag because it was necessary for using <filesystem> module
for createErrors)
add definitions _USE_MATH_DEFINES _CRT_SECURE_NO_DEPRECATE
_SCL_SECURE_NO_DEPRECATE
add linker flag /STACK:8000000

             .src/utilities/CMakeLists.txt
add link flag /WHOLEARCHIVE:lib for
executables regTallies, regSamplers, regGeometries, regPhotonVR, regGenericVR

              .src/kernel/includes/pen_classes.hh
and src/tallies/generic/source/tallyKermaTrackLength.cpp
#include <array>

               .src/kernel/parsers/internalData/source/pen_data.cpp
I suggest not using std::exceptions for parsing string

                .src/lib/auxiliar/CMakeLists.txt
and src/lib/dump/CMakeLists.txt
do not link m.lib missing in VC

                 .src/mains/CMakeLists.txt
  add link flags /WHOLEARCHIVE:lib for building pen_main

**Comment by shirokobrod** [comment]
origin/master branch is merged to fork Pen_red_msvs . All conflicts were resolved. Attached is diff file displaying differences between remote master and  Pen_red_msvs  source files. All changes are necessary for compiling and building project with MSVS 2019 or previous versions supporting C++11. This is list of necessary changes.
1.  src/CMakeLists.txt : compiler options for using AVX2, MPI, M_PI. Setting stack size to 8MB.
2. src/kernel/includes/pen_classes.hh and src/tallies/generic/source/tallyKermaTrackLength.cpp #include <array>
3. src/lib/auxiliar/CMakeLists.txt and src/lib/dump/CMakeLists.txt conditional link with m.lib
4. src/mains/CMakeLists.txt and src/utilities/CMakeLists.txt set linker WHOLEARCHIVE options.
5. src/mains/source/pen_main.cpp Correct calculation "Histories per second" and "Histories per second and thread" on Windows because function clock() works differently on Linux and Windows.
6. src/kernel/parsers/internalData/source/pen_data.cpp include std library headers. I think that using stoi and stod with exceptions for string parsing should be replaced by strtol and strtod without exceptions. These are standard functions and code will remain portable. Other differences in this file results from this replacement.
[penred.zip](https://github.com/PenRed/PenRed/files/6553682/penred.zip)

**Pull request merged**
