### PR TITLE
Implement reinterpretation of negative forcer.

### PR DESCRIPTION
**Pull request by shirokobrod**
forcer is the forcing factor, which must be larger than unity.
 TRICK: a negative input value of forcer, -FN, is assumed to
 mean that a particle with energy E=EPMAX should interact,
 on average, +FN times in the course of its slowing down to
 rest, for electrons and positrons, or along a mean free
 path, for photons. 
 1. forcer > 0, emfp = mfp / force; where mfp is mean free pass, emfp
    is effective mfp.  
    avncol = range / emfp(Emax) is avarage number of interactions on full range down to rest.
    This value is not known when creating configuration file that is why 
    selecting forcer is not intuitive.
 2. forcer < 0 is reinterpreted. forcer = abs(forcer).
    avncol0 = range(Emax) / mfp(Emax)
    forcer_new = forcer / avncol0
    emfp = mfp / forcer_new = mfp * avncol0/ forcer = mfp * range(Emax) / (forcer * mfp(Emax))
    avncol = range / emfp = range(Emax) * forcer * mfp(Emax) / (mfp * range(Emax)) = forcer * mfp(Emax) / mfp 
    avncol ~ forcer

This reinterpretation is implemented both in penelope 2018 and penmain 2018. Attached file shows set forcers and results for penelope 4-x-ray-tube example. Results are slightly different for photon interaction because PenRed calculates photons cross sections slightly differently.
[cmparison.txt](https://github.com/PenRed/PenRed/files/6597020/cmparison.txt)

### CODE REVIEW

**Comment by vigial** [comment]
As you comment, a negative value of the *force* factor is not reinterpreted like the PENELOPE main program (penmain) does. However, we also think it is a desirable feature. I will study your changes to implement this feature.

**Comment by vigial** [comment]
> forcer is the forcing factor, which must be larger than unity.
> TRICK: a negative input value of forcer, -FN, is assumed to
> mean that a particle with energy E=EPMAX should interact,
> on average, +FN times in the course of its slowing down to
> rest, for electrons and positrons, or along a mean free
> path, for photons.
> 
>     1. forcer > 0, emfp = mfp / force; where mfp is mean free pass, emfp
>        is effective mfp.
>        avncol = range / emfp(Emax) is avarage number of interactions on full range down to rest.
>        This value is not known when creating configuration file that is why
>        selecting forcer is not intuitive.
> 
>     2. forcer < 0 is reinterpreted. forcer = abs(forcer).
>        avncol0 = range(Emax) / mfp(Emax)
>        forcer_new = forcer / avncol0
>        emfp = mfp / forcer_new = mfp * avncol0/ forcer = mfp * range(Emax) / (forcer * mfp(Emax))
>        avncol = range / emfp = range(Emax) * forcer * mfp(Emax) / (mfp * range(Emax)) = forcer * mfp(Emax) / mfp
>        avncol ~ forcer
> 
> 
> This reinterpretation is implemented both in penelope 2018 and penmain 2018. Attached file shows set forcers and results for penelope 4-x-ray-tube example. Results are slightly different for photon interaction because PenRed calculates photons cross sections slightly differently.
> [cmparison.txt](https://github.com/PenRed/PenRed/files/6597020/cmparison.txt)

The calculus of photon cross sections in PenRed is, theoretically, exactly the same as the PENELOPE package. In fact, we checked the equivalence of cross sections particle by particle and interaction by interaction for a set of materials and energies. That does not mean that there could not be a bug that affects some specific cases. I have done some modifications in your branch to be able to call the functions using the context class (see pull request https://github.com/shirokobrod/PenRed/pull/2). However, I reproduce the same values as your report in the "cmparison.txt" file. 

I will look further for the reason of that differences

**Comment by vigial** [comment]
I find and fixed (commit f25b842921158fa3ff9f99c34676aed8d837ec4c) a problem which causes that discrepancies. You can find the details in the conversation of the pull request https://github.com/shirokobrod/PenRed/pull/2

**Comment by shirokobrod** [comment]
Thanks!

чт, 24 июн. 2021 г. в 12:30, Vicent Giménez Alventosa <
***@***.***>:

**Pull request merged**
